In [1]:
# conda activate anndata

import re
import os
import sys
import glob
import numpy as np
import pandas as pd
import anndata as ad
from scipy.io import mmwrite
from functools import reduce
from scipy.sparse import csr_matrix

sys.path.append("/mnt/lareaulab/reliscu/code")

from junction2psi import *

In [2]:
os.chdir("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/bulk/hahn_2023/cortex")

## Metadata

In [23]:
sra_meta = pd.read_csv("../SraRunTable.csv")
sra_meta = sra_meta.loc[sra_meta['tissue'].str.contains("cortex", case=False)]

sample_meta = pd.read_csv("../BulkSeq_Aging_metadata.txt", sep="\t")
sample_meta = sample_meta.loc[sample_meta['tissueLong'].str.contains("cortex", case=False)]

In [24]:
set(sra_meta['tissue'])

{'Entorhinal cortex', 'Motor cortex', 'Visual Cortex'}

In [25]:
set(sample_meta["sampleID"].str.replace(r"_[0-9]+", "", regex=True))

{'BulkSeq_cor', 'BulkSeq_ent', 'BulkSeq_vis'}

In [26]:
sra_meta['SampleID'] = "BulkSeq_cor_" + sra_meta['mouse_id_number'].astype("string")
sra_meta.loc[sra_meta['tissue'].str.contains("Ent"), 'SampleID'] = sra_meta.loc[sra_meta['tissue'].str.contains("Ent"), 'SampleID'].str.replace("cor", "ent")
sra_meta.loc[sra_meta['tissue'].str.contains("Vis"), 'SampleID'] = sra_meta.loc[sra_meta['tissue'].str.contains("Vis"), 'SampleID'].str.replace("cor", "vis")

In [27]:
sra_meta["SampleID"].str.replace(r"_[0-9]+", "", regex=True).value_counts()

SampleID
BulkSeq_cor    59
BulkSeq_vis    56
BulkSeq_ent    51
Name: count, dtype: Int64

In [28]:
sra_meta["tissue"].value_counts()

tissue
Motor cortex         59
Visual Cortex        56
Entorhinal cortex    51
Name: count, dtype: int64

In [ ]:
# sample_meta = sample_meta.groupby("sampleID")[["tissueLong", "sex", "age"]].first()

In [30]:
sample_info = sra_meta.merge(sample_meta, left_on="SampleID", right_on="sampleID", how="left")

In [32]:
sample_info.shape

(166, 38)

In [33]:
sample_info.to_csv("hahn_2023_cortex_sampleinfo.csv", index=False)

## Gene counts: STAR

In [70]:
samples = [os.path.basename(p.rstrip("/")) for p in glob.glob("processed/STAR/*") if re.search("SR*", p)]

In [71]:
len(samples)

166

In [72]:
gene_length = pd.read_csv(
    "/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/gene_length.txt",
    sep="\t", header=None, names=["Gene", "Ensembl", "Type", "Length"]
)

In [73]:
cts_list = []
tpm_list = []

for ea in samples:
    star_output = pd.read_csv(
        f"processed/STAR/{ea}/ReadsPerGene.out.tab", 
        header=3, sep="\t", 
        names=["Ensembl", "unstranded", "first_strand", "second_strand"]
    )
    
    df = star_output.merge(
        gene_length, how="left",
        left_on="Ensembl", right_on="Ensembl", 
    )
    df = df.set_index("Gene", drop=True)
    
    counts = df['unstranded']
    rate = counts / df['Length'] * 1000
    tpm = rate / rate.sum() * 1e6
    
    cts_list.append(counts)
    tpm_list.append(tpm)

In [74]:
expr_tpm = pd.concat(tpm_list, axis=1)
expr_counts = pd.concat(cts_list, axis=1)

In [78]:
expr_tpm.columns = samples
expr_counts.columns = samples

In [81]:
expr_counts.to_csv("hahn_2023_cortex_STAR_gene_counts.csv")
expr_tpm.to_csv("hahn_2023_cortex_STAR_gene_TPM.csv")

## SJ counts

In [82]:
def process_SJ_line(line, idx, sj_counts):
    try:
        line = line.decode().rstrip().split('\t')
    except:
        line = line.rstrip().split('\t')

    if line[3] == '1':
        strand = '+'
    elif line[3] == '2':
        strand = '-'
    else:
        strand = 'REMOVE'

    intron_idx = line[0] + ':' + line[1] + '-' + line[2] + ':' + strand
    idx.append(intron_idx)
    sj_counts.append(int(line[6]))
    
    return idx, sj_counts

In [83]:
dtype = np.float64
intron_file = "/mnt/lareaulab/reliscu/data/GENCODE/GRCm39/psix_annotation/intron_file.tab.gz"
intron_table = read_intron_file(intron_file)

In [84]:
intron_table

                                                           intron
ENSMUSG00000025900_ProteinCoding_1_I1      chr1:4363236-4381492:-
ENSMUSG00000025900_ProteinCoding_1_I2      chr1:4381657-4422132:-
ENSMUSG00000025900_ProteinCoding_1_SE      chr1:4363236-4422132:-
ENSMUSG00000025902_ProteinCoding_1_I1      chr1:4562892-4563322:-
ENSMUSG00000025902_ProteinCoding_1_I2      chr1:4563690-4563994:-
...                                                           ...
ENSMUSG00000121920_1_CI                 chr18:36812677-36813568:+
ENSMUSG00000121920_2_CI                 chr18:36813668-36814580:+
ENSMUSG00002076083_1_CI                chr4:156315432-156315541:-
ENSMUSG00002076083_2_CI                chr4:156315631-156316003:-
ENSMUSG00002076083_3_CI                chr4:156316172-156316258:-

[157406 rows x 1 columns]

In [85]:
prefix = "ENSMUSG00000035863_ProteinCoding_1"
rows = intron_table.loc[intron_table.index.str.startswith(prefix)]
rows

                                                          intron
ENSMUSG00000035863_ProteinCoding_1_I1  chr10:79651076-79652625:+
ENSMUSG00000035863_ProteinCoding_1_I2  chr10:79652758-79654874:+
ENSMUSG00000035863_ProteinCoding_1_SE  chr10:79651076-79654874:+

In [86]:
samples = [os.path.basename(p.rstrip("/")) for p in glob.glob("processed/STAR/*") if re.search("SR*", p)]

sj_list = []

colnames = ["chr", "intron_first_base", "intron_last_base", "strand", 
            "intron_motif", "junction_type", "n_unique_jxn_reads",
            "n_multi_jxn_reads", "max_align_overhang"]

for ea in samples:
    sj_name = []
    sj_counts = []
    with open(f"processed/STAR/{ea}/SJ.out.tab", "rb") as fh:
        for line in fh:
            sj_name, sj_counts = process_SJ_line(line, sj_name, sj_counts)
    sj_df = pd.DataFrame(sj_counts, index=sj_name, columns=[ea])
    sj_list.append(sj_df)

In [ ]:
# Note: this takes ~10 minutes

expr_sj = reduce(
    lambda x, y: x.merge(y, how="outer", left_index=True, right_index=True), 
    sj_list
)
expr_sj.shape

(2067751, 166)

In [88]:
intron_table['intron'] = intron_table['intron'].astype(str)
sj_table = pd.merge(intron_table, expr_sj, # Subset to SJs in annotated intron table
                    left_on="intron", how="left", 
                    right_index=True).fillna(0)
sj_table.shape

(157406, 167)

In [89]:
sj_table = sj_table.drop(columns=["intron"])

In [90]:
sj_table.head()

,SRR21355739,SRR21355744,SRR21355733,SRR21355374,SRR21355671,SRR21355241,SRR21354990,SRR21355346,SRR21355701,SRR21355408,...,SRR21355376,SRR21355673,SRR21354992,SRR21355243,SRR21354998,SRR21354976,SRR21355344,SRR21355249,SRR21355703,SRR21355697
ENSMUSG00000025900_ProteinCoding_1_I1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSMUSG00000025900_ProteinCoding_1_I2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
ENSMUSG00000025900_ProteinCoding_1_SE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSMUSG00000025902_ProteinCoding_1_I1,7.0,2.0,11.0,5.0,0.0,4.0,15.0,2.0,10.0,20.0,...,13.0,0.0,0.0,3.0,8.0,5.0,3.0,7.0,5.0,7.0
ENSMUSG00000025902_ProteinCoding_1_I2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [91]:
adata = ad.AnnData(
    X=sj_table.to_numpy().T,
    var=pd.DataFrame(index=sj_table.index),
    obs=pd.DataFrame(index=sj_table.columns),
)

In [92]:
adata.shape

(166, 157406)

In [93]:
adata.write_h5ad("hahn_2023_cortex_STAR_SJ_counts.h5ad")